version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-ts-hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k1wcup7d05e2"
s3_prefix = "sam-ts-hello-world"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
